name: AzuraBoard
version: '${version}'
author: "An5w1r_"
main: cc.azuramc.azuraboard.AzuraBoard
api-version: '1.13'
description: A simple and lightweight scoreboard plugin with multi-language support and PlaceholderAPI integration
website: https://github.com/AzuraMC-Network/AzuraBoard
softdepend:
  - ViaBackwards
  - PlaceholderAPI
folia-supported: ${useFolia}
commands:
  azuraboard:
    description: Main command for AzuraBoard plugin
    aliases: [ab]
    permission: azuraboard.command
  sb:
    description: Quick toggle for scoreboard display
permissions:
  azuraboard.command:
    description: Allows using AzuraBoard commands
    default: op
  azuraboard.toggle:
    description: Allows toggling scoreboard display
    default: true
